version: '3.8'
services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "sh", "-c", "ollama list | grep moondream"]
      interval: 30s
      timeout: 60s
      retries: 10
    # Resource limits for AI models
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    # The entrypoint is now defined in Dockerfile.ollama
  simulation:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=ollama:11434
volumes:
  ollama_data: